---
# tasks file for apache-web

- name: install httpd
  package:
    name: "httpd"
    state: present


- name: copy content
  copy:
    content: "<h1>Hello this is from <b>{{ ansible_host }}</b></h1>"
    dest: /var/www/html/index.html    

- name: service httpd start
  service:
    name: "httpd"
    state: started

